// lib/settings-labels.ts : التسميات العربية ومجموعات حقول الإعدادات — ملف مستقل
export const AR: Record<string, string> = {
  siteName: "اسم المنصة", tagline: "السطر التعريفي", announce: "شريط الإعلان العلوي",
  announceLink: "نص رابط الشريط", contactEmail: "بريد التواصل", contactPhone: "هاتف التواصل",
  footerAbout: "نبذة الفوتر", footerRights: "سطر الحقوق", footerSec1: "عمود الفوتر 1",
  footerSec2: "عمود الفوتر 2", footerSec3: "عمود الفوتر 3",
  navHome: "رابط: الرئيسية", navCourses: "رابط: الدورات", navLibrary: "رابط: المكتبة",
  navQuran: "رابط: القرآنية", navScholars: "رابط: العلماء", navFatwa: "رابط: الفتاوى",
  navNews: "رابط: الأخبار", navVerify: "رابط: التحقق", navAdmission: "رابط: التقديم",
  navDashboard: "رابط: اللوحة", navCta: "زر الهيدر",
  heroKicker: "شارة الواجهة", heroTitle: "عنوان الواجهة", heroDesc: "وصف الواجهة",
  heroBtn1: "زر الواجهة 1", heroBtn2: "زر الواجهة 2", heroBtn3: "زر الواجهة 3",
  homeTracksTitle: "عنوان المسارات", homeFeaturedTitle: "عنوان المميزة",
  homeBooksTitle: "عنوان الكتب", homeNewsTitle: "عنوان الأخبار",
  homeAllLink: "رابط الكل", homeTrackBtn: "زر المسار",
  statTracksNum: "رقم المسارات", statTracksLabel: "تسمية المسارات",
  statCoursesLabel: "تسمية الدورات", statBooksLabel: "تسمية الكتب",
  statOnlineNum: "رقم عن بعد", statOnlineLabel: "تسمية عن بعد",
  coursesTitle: "عنوان الدورات", coursesDesc: "وصف الدورات", coursesAll: "زر الكل",
  libraryTitle: "عنوان المكتبة", libraryDesc: "وصف المكتبة", libraryRead: "زر القراءة",
  quranTitle: "عنوان القرآنية", quranDesc: "وصف القرآنية",
  quranCourses: "عنوان دورات القرآن", quranLessons: "عنوان التجويد",
  quranIjazaTitle: "عنوان الإجازة", quranIjazaDesc: "وصف الإجازة", quranIjazaBtn: "زر الإجازة",
  quranEnter: "زر ادخل الدورة", quranWatch: "زر مشاهدة", quranSoon: "نص قريبا",
  scholarsTitle: "عنوان العلماء", scholarsDesc: "وصف العلماء",
  fatwaTitle: "عنوان الفتاوى", fatwaDesc: "وصف الفتاوى",
  newsTitle: "عنوان الأخبار", newsDesc: "وصف الأخبار",
  verifyTitle: "عنوان التحقق", verifyDesc: "وصف التحقق",
  verifyLabel: "تسمية حقل الكود", verifyBtn: "زر التحقق",
  verifyNotFound: "رسالة عدم وجود شهادة", verifyPlaceholder: "مثال حقل الكود",
  admissionTitle: "عنوان التقديم", admissionDesc: "وصف التقديم",
  admissionName: "تسمية الاسم", admissionPhone: "تسمية الهاتف",
  admissionTrack: "تسمية المسار", admissionCourse: "تسمية الدورة",
  admissionSubmit: "زر الإرسال", admissionNoCourses: "نص لا توجد دورات",
  admissionOkTitle: "عنوان نجاح التقديم", admissionOkDesc: "وصف نجاح التقديم",
  emptyCourses: "نص لا توجد دورات", emptyBooks: "نص لا توجد كتب",
  emptyNews: "نص لا توجد أخبار", emptyGeneral: "نص فارغ عام",
  certTitle: "عنوان الشهادة", certSubtitle: "سطر التشهد", certFooter: "تذييل الشهادة",
  certSignName: "اسم الموقع", certSignTitle: "صفة الموقع",
  certPrintBtn: "زر الطباعة", certVerifyLink: "رابط التحقق",
  certCoursePrefix: "بادئة الدورة", certGradeLabel: "تسمية التقدير",
  certDateLabel: "تسمية التاريخ", certCodeLabel: "تسمية الرقم",
  loginTitle: "عنوان الدخول", loginDesc: "وصف الدخول",
  loginEmail: "تسمية البريد", loginPass: "تسمية كلمة المرور", loginBtn: "زر الدخول",
  loginShow: "زر إظهار", loginHide: "زر إخفاء",
  loginErrTitle: "عنوان خطأ الدخول", loginErrDesc: "وصف خطأ الدخول",
  loginForgot: "نص نسيت البيانات",
  detailJoin: "زر الالتحاق", detailAll: "زر كل الدورات", detailLessons: "عنوان الدروس",
  detailWatch: "زر مشاهدة الدرس", detailSoon: "نص قريبا",
  detailNoVideo: "نص لا يوجد فيديو", detailFree: "نص مجاني",
  cardDetails: "زر التفاصيل", cardHours: "تسمية الساعات", cardFree: "نص مجاني بالكارت",
  cardCurrency: "العملة",
  themeMode: "وضع الثيم", themePrimary: "اللون الأساسي", themeSecondary: "اللون الثانوي",
  themeGold: "اللون الذهبي", themeBg: "لون الخلفية", themeCard: "لون البطاقات",
  themeText: "لون النص", themeMut: "لون النص الثانوي", themeBr: "لون الحدود",
};

export const GROUPS: { title: string; keys: string[] }[] = [
  { title: "الهوية والتواصل والفوتر", keys: ["siteName", "tagline", "announce", "announceLink", "contactEmail", "contactPhone", "footerAbout", "footerRights", "footerSec1", "footerSec2", "footerSec3"] },
  { title: "القائمة والأزرار والواجهة", keys: ["navHome", "navCourses", "navLibrary", "navQuran", "navScholars", "navFatwa", "navNews", "navVerify", "navAdmission", "navDashboard", "navCta", "heroKicker", "heroTitle", "heroDesc", "heroBtn1", "heroBtn2", "heroBtn3", "homeTracksTitle", "homeFeaturedTitle", "homeBooksTitle", "homeNewsTitle", "homeAllLink", "homeTrackBtn", "statTracksNum", "statTracksLabel", "statCoursesLabel", "statBooksLabel", "statOnlineNum", "statOnlineLabel"] },
  { title: "الدورات والمكتبة والقرآنية", keys: ["coursesTitle", "coursesDesc", "coursesAll", "libraryTitle", "libraryDesc", "libraryRead", "quranTitle", "quranDesc", "quranCourses", "quranLessons", "quranIjazaTitle", "quranIjazaDesc", "quranIjazaBtn", "quranEnter", "quranWatch", "quranSoon", "detailJoin", "detailAll", "detailLessons", "detailWatch", "detailSoon", "detailNoVideo", "detailFree"] },
  { title: "العلماء والفتاوى والأخبار", keys: ["scholarsTitle", "scholarsDesc", "fatwaTitle", "fatwaDesc", "newsTitle", "newsDesc"] },
  { title: "التحقق والتقديم والدخول", keys: ["verifyTitle", "verifyDesc", "verifyLabel", "verifyBtn", "verifyNotFound", "verifyPlaceholder", "admissionTitle", "admissionDesc", "admissionName", "admissionPhone", "admissionTrack", "admissionCourse", "admissionSubmit", "admissionNoCourses", "admissionOkTitle", "admissionOkDesc", "loginTitle", "loginDesc", "loginEmail", "loginPass", "loginBtn", "loginShow", "loginHide", "loginErrTitle", "loginErrDesc", "loginForgot", "emptyCourses", "emptyBooks", "emptyNews", "emptyGeneral"] },
  { title: "نصوص الشهادة الرسمية", keys: ["certTitle", "certSubtitle", "certFooter", "certSignName", "certSignTitle", "certPrintBtn", "certVerifyLink", "certCoursePrefix", "certGradeLabel", "certDateLabel", "certCodeLabel"] },
  { title: "المظهر والألوان", keys: ["themeMode", "themePrimary", "themeSecondary", "themeGold", "themeBg", "themeCard", "themeText", "themeMut", "themeBr"] },
];
